source "https://rubygems.org"

gem "rails", "~> 7.0"
gem "pg", "~> 1.5"
# Typosquat: "raisl" is edit distance 1 from "rails"
gem "raisl", "~> 1.0"
# Dep confusion: internal-looking gem without private source
gem "company-internal", "~> 1.0"