source "https://rubygems.org"

gem "rails", "~> 7.0"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "devise", "~> 4.9"

group :development, :test do
  gem "rspec-rails", "~> 6.0"
end

group :development do
  gem "listen", "~> 3.8"
end