# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import picodome_pb2 as picodome__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in picodome_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PicoDomeServiceStub:
    """─── Service ─────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Scan = channel.unary_unary(
                '/picodome.PicoDomeService/Scan',
                request_serializer=picodome__pb2.ScanRequest.SerializeToString,
                response_deserializer=picodome__pb2.ScanResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/picodome.PicoDomeService/Health',
                request_serializer=picodome__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=picodome__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/picodome.PicoDomeService/GetPolicy',
                request_serializer=picodome__pb2.PolicyGetRequest.SerializeToString,
                response_deserializer=picodome__pb2.PolicyGetResponse.FromString,
                _registered_method=True)
        self.QueryAudit = channel.unary_unary(
                '/picodome.PicoDomeService/QueryAudit',
                request_serializer=picodome__pb2.AuditQueryRequest.SerializeToString,
                response_deserializer=picodome__pb2.AuditQueryResponse.FromString,
                _registered_method=True)


class PicoDomeServiceServicer:
    """─── Service ─────────────────────────────────────────────────────────────────

    """

    def Scan(self, request, context):
        """Submit a sandbox scan job and wait for result
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """Get a policy by name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAudit(self, request, context):
        """Query the audit log
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PicoDomeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=picodome__pb2.ScanRequest.FromString,
                    response_serializer=picodome__pb2.ScanResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=picodome__pb2.HealthCheckRequest.FromString,
                    response_serializer=picodome__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=picodome__pb2.PolicyGetRequest.FromString,
                    response_serializer=picodome__pb2.PolicyGetResponse.SerializeToString,
            ),
            'QueryAudit': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAudit,
                    request_deserializer=picodome__pb2.AuditQueryRequest.FromString,
                    response_serializer=picodome__pb2.AuditQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'picodome.PicoDomeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('picodome.PicoDomeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PicoDomeService:
    """─── Service ─────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/picodome.PicoDomeService/Scan',
            picodome__pb2.ScanRequest.SerializeToString,
            picodome__pb2.ScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/picodome.PicoDomeService/Health',
            picodome__pb2.HealthCheckRequest.SerializeToString,
            picodome__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/picodome.PicoDomeService/GetPolicy',
            picodome__pb2.PolicyGetRequest.SerializeToString,
            picodome__pb2.PolicyGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAudit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/picodome.PicoDomeService/QueryAudit',
            picodome__pb2.AuditQueryRequest.SerializeToString,
            picodome__pb2.AuditQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
