{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "picodome-admission.fullname" . }}
  labels:
    {{- include "picodome-admission.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "picodome-admission.selectorLabels" . | nindent 6 }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
{{- end }}
