{{- if .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "serve.fullname" . }}-tokens
  labels:
    {{- include "serve.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-tokens: {{ .Values.auth.tokens | default (printf "picosentry-admin-%s" (randAlphaNum 32)) | quote }}
{{- end }}